### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by endrebak** [dariober/ASCIIGenome#11]
```
ASCIIGenome gencode.v25.annotation.gtf
Initializing coordinates... Reading file 'gencode.v25.annotation.gtf'...Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at java.lang.String.replace(String.java:2239)
	at tracks.IntervalFeature.intervalFeatureFromGtfLine(IntervalFeature.java:146)
	at tracks.IntervalFeature.<init>(IntervalFeature.java:60)
	at tracks.IntervalFeatureSet.loadFileIntoIntervalMap(IntervalFeatureSet.java:217)
	at tracks.IntervalFeatureSet.<init>(IntervalFeatureSet.java:58)
	at tracks.TrackIntervalFeature.<init>(TrackIntervalFeature.java:25)
	at samTextViewer.Main.main(Main.java:201)
	... 5 more
```

Perhaps you should add something to the docs about how to increase the memory/GC size? I have no idea how to do it.

Tried on OS X and Ubuntu.

**Comment by endrebak** [comment]
Okay, so the answer is in the README. Great, my bad!

But if the standard setting is too low to open a common file type, it is probably too low.

**Comment by endrebak** [comment]
Also, how do I increase the GC in the brew installed version?

**Comment by dariober** [comment]
>Also, how do I increase the GC in the brew installed version?

I think you should locate where `ASCIIGenome` bash script is and then change the `-Xmx` option. This should do:

```
which ASCIIGenome ## Should return /usr/local/bin/ or something like that
vi /path//to/ASCIIGenome ## Use your favourite text editor and edit -Xmx as preferred
```

I might increase the default memory allocation, I thought  1.5GB was reasonable...
