### ISSUE TITLE
Error stack with "Could not initilize from file"

### ISSUE THREAD

**Issue by sblab-bioinformatics** [dariober/ASCIIGenome#24]
If there are you try to load a single invalid file, you get an ugly error stack. Fix it by issuing a friendlier message. E.g.

```
ASCIIGenome du.tmp.txt
Initializing coordinates... 
Could not initilize from file du.tmp.txt
Reading file 'du.tmp.txt'...First line skipped. Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: intervalFeatureFromBedLine: Invalid bed line:
[20, /nas/sblab_data1/berald01/repository/bwameth/ear020_OXBS.ecoli_fastqc/Icons]
	at tracks.IntervalFeature.intervalFeatureFromBedLine(IntervalFeature.java:115)
	at tracks.IntervalFeature.<init>(IntervalFeature.java:57)
	at tracks.IntervalFeatureSet.loadFileIntoIntervalMap(IntervalFeatureSet.java:217)
	at tracks.IntervalFeatureSet.<init>(IntervalFeatureSet.java:58)
	at tracks.TrackIntervalFeature.<init>(TrackIntervalFeature.java:25)
	at samTextViewer.Main.main(Main.java:208)
	... 5 more
```

**Comment by dariober** [comment]
Fixed in branches/color_etc
