### ISSUE TITLE
Error with `seqRegex ^`

### ISSUE THREAD

**Issue by dariober** [dariober/ASCIIGenome#25]
Searching for `seqRegex ^` gives:

```
Invalid coordinates: 1 0
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: exceptions.InvalidGenomicCoordsException
	at tracks.IntervalFeature.validateIntervalFeature(IntervalFeature.java:190)
	at tracks.IntervalFeature.intervalFeatureFromBedLine(IntervalFeature.java:139)
	at tracks.IntervalFeature.<init>(IntervalFeature.java:57)
	at samTextViewer.GenomicCoords.findRegex(GenomicCoords.java:757)
	at samTextViewer.Main.main(Main.java:299)
	... 5 more
```

**Comment by dariober** [comment]
Fixed after refactoring seqRegex.
