### ISSUE TITLE
trim with window resizing

### ISSUE THREAD

**Issue by dariober** [dariober/ASCIIGenome#37]
`trim` doesn't play very well with terminal window resizing try:

```
ASCIIGenome hg19_genes_head.gtf.gz -r chr1:11583-12359
```

Then execute `trim` -> ok. Then resize terminal window to make it smaller, `trim` again. You get:

```
java.lang.IndexOutOfBoundsException: Index: 85, Size: 85
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.set(ArrayList.java:444)
	at tracks.TrackIntervalFeature.printToScreenOneLine(TrackIntervalFeature.java:361)
	at tracks.TrackIntervalFeature.printToScreen(TrackIntervalFeature.java:312)
	at samTextViewer.TrackProcessor.iterateTracks(TrackProcessor.java:66)
	at samTextViewer.InteractiveInput.processInput(InteractiveInput.java:325)
	at samTextViewer.Main.main(Main.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
```

~Then resize window again to make it larger. zoom out and go to another feature. `trim` again. the window has become smaller.~

You probably need to play with getUserWindowSize() in the trim method.

There are other issues with trim. Make this method undocumented for now

**Comment by dariober** [comment]
Issue closed at least for now since `trim` is not that useful anyway, leave it undocumented.
