### ISSUE TITLE
next with feature close to position 1

### ISSUE THREAD

**Issue by dariober** [dariober/ASCIIGenome#7]
Reproduce bug:

```
echo -e "chr1\t1000\t10000" > test.bed
ASCIIGenome -g hg19 -r chr1:1 test.bed
```

Then issue `next` command, you get:

```
Invalid coordinates: from: -39499;to: 50501Resetting to initial 1-2147483647
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: exceptions.InvalidGenomicCoordsException
	at tracks.IntervalFeatureSet.getFeaturesInInterval(IntervalFeatureSet.java:97)
	at tracks.TrackIntervalFeature.update(TrackIntervalFeature.java:38)
	at tracks.TrackIntervalFeature.<init>(TrackIntervalFeature.java:32)
	at samTextViewer.GenomicCoords.findRegex(GenomicCoords.java:701)
	at samTextViewer.Main.main(Main.java:294)
	... 5 more
```

Reason:

If `next` is executed from position 1 (or there about) and the first feature is close to 1, after extension left and right you get a negative start position which is reset to 1-2147483647 if a genome file is present you then get this exception.

**Comment by dariober** [comment]
Fixed. `GenomicCoords.correctCoordsAgainstSeqDict()` didn't check for `from < 1` when dictionary is present.
