### ISSUE TITLE
awk function with `featureDisplayMode`

### ISSUE THREAD

**Issue by dariober** [dariober/ASCIIGenome#80]
`featureDisplayMode -c` applied after `awk` with an internal function like `getInfoTag()` throws an exception:

```
ASCIIGenome -r chr8:5000000-15000000 --debug 2 -ni -nf -x 'awk getInfoTag("FOLD_CHANGE_LOG")>2 && featureDisplayMode -c' test_data/ovl.vcf

java.lang.NullPointerException
	at tracks.TrackIntervalFeature.printToScreenOneLine(TrackIntervalFeature.java:594)
	at tracks.TrackIntervalFeature.printToScreen(TrackIntervalFeature.java:490)
	at tracks.Track.concatTitleAndTrack(Track.java:593)
	at samTextViewer.TrackProcessor.iterateTracks(TrackProcessor.java:74)
	at samTextViewer.InteractiveInput.processInput(InteractiveInput.java:424)
	at samTextViewer.Main.main(Main.java:160)
```

Although `awk` itself is fine:

```
ASCIIGenome -r chr8:5000000-15000000 --debug 2 -ni -nf -x 'awk $CHROM=="chr8" && featureDisplayMode -c' test_data/ovl.vcf
```

**Comment by dariober** [comment]
Fixed in v1.12. Bug was unrelated to `awk` and vcf. Instead, problem was in `Utils.mergeIntervalFeatures()` where the ideogram was created for only the first merged feature.
