### ISSUE TITLE
Even after upgrading from java 7 to java 8 , I still get the following error

### ISSUE THREAD

**Issue by santhiya85** [dariober/ASCIIGenome#82]
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/mycompany/wordcounthadoop/WordCount : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
------------------------------------------------------------------------
BUILD FAILURE

**Comment by santhiya85** [comment]
actually I have executed wordcount program available on github thru
netbeans IDE using maven.......................

Hadoop version 2.6.0
Netbeans ID E   8.2
Java 1.8

Can u pls help me to sort out this error




*Santhiya.K*

*PhD Research Scholar*

*Department of Computer Applications*

*Bharathiar University*
*Coimbatore - 641 046*
