### ISSUE TITLE
error opening bam file

### ISSUE THREAD

**Issue by jahann** [dariober/ASCIIGenome#84]
Hi,

I try to view a bam file but it generates an error. I just provide the reference which seems valid and the bam file, not other annotations.

ASCIIGenome -fa ../ref/2A.fa ../bamsource/2A/16NASWI0308.bam

Indexing '../ref/2A.fa'.
Initializing coordinates... Done from: ../bamsource/2A/16NASWI0308.bam
Exception when processing alignment for BAM index K00289:33:HFCN3BBXX:7:1217:11495:18564 1/2 113b aligned read.
htsjdk.samtools.SAMException: Exception when processing alignment for BAM index K00289:33:HFCN3BBXX:7:1217:11495:18564 1/2 113b aligned read.
        at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:124)
        at htsjdk.samtools.SAMFileWriterImpl.close(SAMFileWriterImpl.java:204)
        at samTextViewer.Utils.sortAndIndexSamOrBam(Utils.java:2248)
        at tracks.TrackPileup.<init>(TrackPileup.java:71)
        at tracks.TrackSet.<init>(TrackSet.java:63)
        at samTextViewer.Main.main(Main.java:110)
Caused by: htsjdk.samtools.SAMException: Exception creating BAM index for record K00289:33:HFCN3BBXX:7:1217:11495:18564 1/2 113b aligned read.
        at htsjdk.samtools.BAMIndexer.processAlignment(BAMIndexer.java:92)
        at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:121)
        ... 5 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 32784
        at htsjdk.samtools.BinningIndexBuilder.processFeature(BinningIndexBuilder.java:136)
        at htsjdk.samtools.BAMIndexer$BAMIndexBuilder.processAlignment(BAMIndexer.java:195)
        at htsjdk.samtools.BAMIndexer.processAlignment(BAMIndexer.java:90)
        ... 6 more
Cannot add ../bamsource/2A/16NASWI0308.bam; skipping

I tried several and they all seem to fail.

**Comment by dariober** [comment]
Hi- There may be something odd with your alignments. First thing I would try to do is to reindex the bam files with e.g. `samtools index bamsource/2A/16NASWI0308.bam`

It may be good to pass the bam file through [picard/ValidateSamFile](https://broadinstitute.github.io/picard/command-line-overview.html#ValidateSamFile) to check for inconsistencies. (I tried to make ASCIIGenome tolerant to some errors but not everything). The problem appears to be with (at least) read `K00289:33:HFCN3BBXX:7:1217:11495:18564`. Can you post this read, please? E.g., send the output of:

```
samtools view bamsource/2A/16NASWI0308.bam | grep 'K00289:33:HFCN3BBXX:7:1217:11495:18564'
```

If there is no confidential information, can you also post the header of the bam file? E.g. 

```
samtools view -H bamsource/2A/16NASWI0308.bam
```

Can you also tell how this bam file was produced? Which aligner did you use and what processing it went through?

Thanks!
