### ISSUE TITLE
Initialize from SAM file with missing chromosome

### ISSUE THREAD

**Issue by dariober** [dariober/ASCIIGenome#86]
If the first record of a sam file has "read unmapped" bit set, its contig is null and ASCIIGenome (v1.14) gives:

```
ASCIIGenome test_data/missing_contig.sam
Initializing coordinates... Done from: test_data/missing_contig.sam

Cannot find chromosome 'null' in sequence dictionary.
Exception in thread "main" exceptions.InvalidGenomicCoordsException
	at samTextViewer.GenomicCoords.<init>(GenomicCoords.java:92)
	at samTextViewer.GenomicCoords.<init>(GenomicCoords.java:109)
	at samTextViewer.Main.main(Main.java:114)
```

With `test_data/missing_contig.sam`:

```
@HD VN:1.4  SO:coordinate
@SQ SN:chr7 LN:1091
r1  69  chr7    10  0   *   =   10  0   CCCCTCTCCT    *
r1  137 chr7    10  0   10M =   10  0   GAAAGGTGGG    *
```

**Comment by dariober** [comment]
Fixed in (forthcoming) v1.15. See https://github.com/dariober/ASCIIGenome/commit/f0f89cfbdd6c8fb2e6018873ee988a6ff20a2be9
